### ISSUE TITLE
Builds fail due to package mismatch

### ISSUE THREAD

**Issue by akgokce** [brain-score/vision#1233]
The package of name `brainio` is changed to `brainscore-brainio`  and now builds fail since the package cannot be installed. Need to modify `brainscore_core` to use the updated name, see[ this pull request](https://github.com/brain-score/core/pull/128).

**Comment by KartikP** [comment]
Hi @akgokce! Thanks for pointing that out. We're in the process of adding all the repos to pypi, and suspect the name switch arose because brainio already exists for a different project. I'll let @samwinebrake chime in on this

**Comment by samwinebrake** [comment]
Good catch! Merged your changes in core; let me know if you still run into issues!
