### ISSUE TITLE
Missing attribute 'Defaults.stratification_coord' in https://github.com/brain-score/vision/brainscore_vision.metric_helpers.py

### ISSUE THREAD

**Issue by ddcoggan** [brain-score/vision#532]
https://github.com/brain-score/vision/brainscore_vision.model_helpers.check_submissions.check_model.py crashes on line 73 when referring to Defaults.stratification_coord in https://github.com/brain-score/vision/brainscore_vision.metric_helpers.py

**Comment by mike-ferguson** [comment]
Hi @ddcoggan, thanks for opening an Issue. @mschrimpf any thoughts here, possibly an xarray recent update?

**Comment by mschrimpf** [comment]
We have tried to remove the default and instead moved this choice explicitly into each benchmark (e.g. [here](https://github.com/brain-score/vision/blob/842ebd295456b7e5ffb31ded896be4929809a53a/brainscore_vision/benchmarks/majajhong2015/benchmark.py#L23)).

We should do the same for the [MockBenchmark](https://github.com/brain-score/vision/blob/master/brainscore_vision/model_helpers/check_submission/check_models.py#L60). Specifically, we can now simplify the specification of the metric in that class to `self._similarity_metric = load_metric('pls', crossvalidation_kwargs=dict(stratification_coord='object_name'))`.
