### ISSUE TITLE
Link to sample zip file missing?

### ISSUE THREAD

**Issue by ThomasYerxa** [brain-score/vision#541]
Hello, I am attempting to complete the submission tutorials and the "deep dive 1" (https://www.brain-score.org/tutorial/deepdive_1) requires downloading a sample model.zip file and it appears the hyperlink is broken?

Is there any other way to download this file/is this an issue on my end? Thanks in advance!

**Comment by ThomasYerxa** [comment]
Apologies, this is a duplicate of [this issue from brainscore.web](https://github.com/brain-score/brain-score.web/issues/225) and I was able to download the zip from [here](https://github.com/brain-score/brain-score.web/blob/web_2.0_fixes/static/benchmarks/packaging_tutorial.zip).  

Not sure whether or not to close this issue or keep it open for visibility until the website updates are merged?

**Comment by samwinebrake** [comment]
Thanks for the heads up! Should be fixed with [PR #224](https://github.com/brain-score/brain-score.web/pull/224) in brainscore.web that was merged today!
