### ISSUE TITLE
Score format maybe outdated in the tutorial and readme

### ISSUE THREAD

**Issue by YudiXie** [brain-score/vision#562]
I found that the returned score format is perhaps outdated in this tutorial:
https://www.brain-score.org/tutorial/quickstart

and the readme on the github page:
https://github.com/brain-score/vision

```
xarray.Score (aggregation: 2)
array([0.01538053, 0.00571393])
Coordinates:
* aggregation  (aggregation) U6 'center' 'error'
Attributes:
raw:                   xarray.Score (aggregation: 2)>\narray([0.10192326...
ceiling:               xarray.Score (aggregation: 2)>\narray([8.21840601...
model_identifier:      pixels
benchmark_identifier:  dicarlo.MajajHong2015.IT-pls
```

In my recent usage, I believe the `aggregation` is removed and should be replaced by something like `score.item()` and `score.error.item()`?

**Comment by mike-ferguson** [comment]
Hey @YudiXie thanks for catching this! You are correct, and I will update it tomorrow. This is also related to your other issue (#563), so I will address this tomorrow as well. Thanks again!
