### ISSUE TITLE
File already exists error handling

### ISSUE THREAD

**Issue by ShreyaKapoor18** [brain-score/vision#580]
https://github.com/brain-score/vision/blob/2fe192fad2636ed41e48b07dcaa966dc28864035/brainscore_vision/benchmark_helpers/screen.py#L49-L50

I tried to run multiple benchmarks locally and after running 1 benchmark I got the error 
```
 File "/home/hpc/miniconda3/envs/py38objaverse/lib/python3.8/site-packages/brainscore_vision/benchmark_helpers/screen.py", line 50, in _place_on_screen
    target_dir.mkdir(parents=True, exist_ok=False)
FileExistsError: [Errno 17] File exists: /.brain-score/no_spec/stimuli_on_screen/movshon.FreemanZiemba2013.aperture-public--target8--source4'
```

I think changing the code to the following might be helpful for the community
```
    if os.path.exists(target_dir):
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True, exist_ok=False)
  ```

**Comment by deirdre-k** [comment]
Just opened PR #606 addressing this issue, thanks for raising it!
