### ISSUE TITLE
Upload model checkpoint files to S3

### ISSUE THREAD

**Issue by shehadak** [brain-score/vision#586]
The repository currently contains multiple large files that were inadvertently added as model weights via website model submissions, particularly in:

- [brainscore_vision/models/resnet50_eMMCR_Vanilla](https://github.com/brain-score/vision/blob/master/brainscore_vision/models/resnet50_eMMCR_Vanilla)
- [brainscore_vision/models/resnet50_eMMCR_eqp10_lm1](https://github.com/brain-score/vision/blob/master/brainscore_vision/models/resnet50_eMMCR_eqp10_lm1)
- [brainscore_vision/models/dbp_resnet50_julios](https://github.com/brain-score/vision/blob/master/brainscore_vision/models/dbp_resnet50_julios)

The large files need to be uploaded to S3 and their model-loading scripts should be updated to download the model weights as needed. Ideally, the large files need to also be removed from the Git history of this repository.

For future submissions, [a size limit ](https://github.com/brain-score/brain-score.web/blob/master/benchmarks/views/user.py#L275)is imposed on each website model submission (currently set to 50MB).

**Comment by mschrimpf** [comment]
if Github allows us to commit and push these files, is the "need" to upload to S3 mostly a best-practices one, or is there another reason?

**Comment by kvfairchild** [comment]
> if Github allows us to commit and push these files, is the "need" to upload to S3 mostly a best-practices one, or is there another reason?

The time to clone the repo is noticeably longer with just these files.

**Comment by YudiXie** [comment]
Meanwhile, GitHub has some recommended storage cap for the size of the overall repo (Link)[https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#repository-size-limits]. As time goes by, if we keep allowing people to upload weights to the repo, the repo will become very large that takes a lot of time to clone and will exceed storage cap.

**Comment by deirdre-k** [comment]
* Files moved to S3, code updated (see PR #672)

TODO: 
* check test coverage/add tests (see PR #673)
* Remove files from git history (will do once PR is merged)
