### ISSUE TITLE
Delete automerged branches

### ISSUE THREAD

**Issue by samwinebrake** [brain-score/vision#596]
Currently, whenever a web submission is automerged, its corresponding branch is not deleted, which is causing a rapid increase of the amount of branches in the repository. 

The process of automatic branch deletion after automerge should be added to the automerge workflow in order to maintain an organized codebase.

**Comment by mschrimpf** [comment]
![image](https://github.com/brain-score/vision/assets/5308236/25dcee93-d7ea-41fc-b5b5-86c07b20f8a8)
exhibit A
