### ISSUE TITLE
Verify Model Score Reproduceability

### ISSUE THREAD

**Issue by pellegreene** [brain-score/vision#661]
Models are seeing scores that vary the website on some benchmarks.

We need to figure out why this could be happening. Did something in the code change? Are there benchmarks that produce incorrect scores? Did our model weights change at all?

**Comment by pellegreene** [comment]
So far I've evaluated Alexnet across a number of benchmarks. Most line up with the website, a handful does not. Looking through the benchmark files, not seeing any changed.

With that, going to revert my local git version and see how things looked in 2019/2020. If the score is consistent, then we can call it a benchmark problem and solve from there.

**Comment by deirdre-k** [comment]
Missing model code for a number of models, Ethan to track down into one place and then work with prioritized list of models

**Comment by pellegreene** [comment]
Putting this on-hold since models are not converted. All associated issues are also on-hold.

**Comment by deirdre-k** [comment]
Issue goals:

- [ ] Run scoring for all benchmark comp and top 25 models
- [ ] Identify mismatched scores
