### ISSUE TITLE
Centralize code for all models

### ISSUE THREAD

**Issue by deirdre-k** [brain-score/vision#678]
Model code is not in any centralized place right now. We want to track down all code and put it into one shared place.

Plan:
* Upload to brainscore-vision Git branch to get it all in one centralized, tracked place
* AirTable (list with isOnGithub, reproducesOnMajojHong (+ others), isConverted, isMerged, reproducesOnAll)

Open Questions
* Resolving models with changed identifiers
* Get BrainTree models

**Comment by pellegreene** [comment]
https://airtable.com/invite/l?inviteId=invNGt9gVRFguJrUQ&inviteToken=95f8cfa37a21e6c1f93e84d8660cfcf40a3ae32ae5f5ffb81c8bf09f3522a1e5&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

Airtable link above! Will be updating the model statuses as I come across them.

**Comment by deirdre-k** [comment]
To ask: How many models are private?

**Comment by pellegreene** [comment]
Two models are private in the whole repo, so we can have a lot of these in our BS repo. Waiting on Martin to track down which of those it is before proceeding.

**Comment by pellegreene** [comment]
21 models on the leaderboard need to be removed from the model pool before we can upload them to a public space.
