### ISSUE TITLE
Quickstart Step 1: Incompatible pip version causes package installation to fail

### ISSUE THREAD

**Issue by Zhengro** [brain-score/vision#686]
The currently provided commands for installing packages is insufficient.
<img width="753" alt="image" src="https://github.com/brain-score/vision/assets/44876183/0a6acfd8-d5c3-4edb-9511-218ce4a2850a">

Because it doesn't require the proper version of `pip`. In order to run `python -m pip install -e .`, the `pip` version must satisfy `>=21.3` (`python>=3.7` does not necessarily guarantee this). More details can be found in the section "How to install a package in editable mode?" in this answer https://stackoverflow.com/a/66472800

An example of error message when using `pip` version 21.2.4:
`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /PROJECT_DIR/vision
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)`

A quick fix is to add another command `python -m pip install --upgrade pip. # make sure pip>=21.3` before `python -m pip install -e .` Note that this additional command is already included in several setup files in this repo but missing in Quickstart Step 1!

Please consider have a fix for this issue to remove a potential obstacle for anyone getting started with it. It also looks confusing regarding the section "Local installation" in README. Not sure if it is a bit out of date.

**Comment by mike-ferguson** [comment]
Thanks! We will address this soon
