### ISSUE TITLE
Resubmisison via the website failures

### ISSUE THREAD

**Issue by ThomasYerxa** [brain-score/vision#714]
In recent submissions a (seemingly random across submissions) subset of benchmarks fail/error out. In the past I have simply resubmitted the failed model/benchmark via the website, but these runs seem to consistently cause an error when setting up the environment (example log [here](http://braintree.mit.edu:8080/job/score_plugins/211/parsed_console/)). 

Thanks in advance for your help!

**Comment by samwinebrake** [comment]
This looks to be an issue with the domain not set to 'vision' within the parameters of the score plugins job (see [here](http://braintree.mit.edu:8080/job/score_plugins/211/parameters/) where the domain parameter is blank). Looking into why this occurred now @ThomasYerxa

**Comment by ThomasYerxa** [comment]
Thanks to you both for looking into this, let me know when I should resubmit evaluations

**Comment by samwinebrake** [comment]
@mike-ferguson looking at parameters for newly resubmitted jobs, it looks like they are still missing domain and email

(see [here](http://braintree.mit.edu:8080/job/score_plugins/242/parameters/))

**Comment by ThomasYerxa** [comment]
Email and domain parameter fields are populated in latest re-submission
