### ISSUE TITLE
Error catching in unit testing

### ISSUE THREAD

**Issue by samwinebrake** [brain-score/vision#735]
It seems that, in some PRs, errors in the unit testing are not causing the jobs to fail (see PR #719 and #720 ), which can lead to failing model automerge. Look into why these errors are not being parsed correctly in Jenkins.

**Comment by pellegreene** [comment]
Changed the configuration of the Jenkins builds to fail if anything else in the pipeline fails. More [recent Jenkins](http://braintree.mit.edu:8080/job/unittest_plugins/1132/console) builds seem to be failing in ways that others did not. Not sure if we can say this is satisfied without observing it over time. Either way, they are currently not passing builds with failures in them. Would this satisfy this ticket @samwinebrake?

**Comment by samwinebrake** [comment]
@pellegreene The failing occurring in the linked jenkins job is unrelated to this issue. That looks like it was due to awscli not being available in the anaconda channel of conda install which has been updated. 

I thought the issue was related to how general plugin test results are not recorded in the xml, so builds were being passed that failed them. For instance, [this recent jenkins build ](http://braintree.mit.edu:8080/job/unittest_plugins/1134/console) shows the generic plugin tests passing, but the bottom of the log states: 

`download: s3://brainscore-unittests/vision/result_vision_1134_plugins.xml to ./result_vision_1134_plugins.xml
Recording test results
None of the test reports contained any result`

Showing that these general results are not written to the log (although in this case they are passing, if generic plugin tests had failed, they still wouldn't be written to the log and the build would pass).

**Comment by pellegreene** [comment]
PR'd the change to write generic tests to the parsed XML file in the Core repo. This PR can be found [here](https://github.com/brain-score/core/pull/102).
