### ISSUE TITLE
Automerge/Score-Plugin Actions Skipped

### ISSUE THREAD

**Issue by ThomasYerxa** [brain-score/vision#791]
Several recent web submission PRs (#781 #782 #783 #785 #788 #789) have passed all tests but the automerge and subsequent actions were skipped. Not sure if this is related to #689?  

Thanks in advance for looking into this!

**Comment by samwinebrake** [comment]
Fixed!

**Comment by samwinebrake** [comment]
Seems to still be occurring, reopening until fixed completely.

**Comment by samwinebrake** [comment]
Fixed!
