### ISSUE TITLE
Run unreproducible competition models on 1.0

### ISSUE THREAD

**Issue by deirdre-k** [brain-score/vision#807]
Run the models and then analyze *why* they are mismatched.

Then, based on findings, decide which score should stay in the database.

**Comment by mike-ferguson** [comment]
Models to score om 1.0: 

- [ ] `cvt_cvt-w24-384-in22k_finetuned-in1k_4` (website score:0.488, 2.0 Score: 0.477)
- [ ] `effnetb1_cutmixpatch_augmix_robust32_avge4e7_manylayers_324x288`: (website score:0.539, 2.0 Score: 0.560)
- [ ] `custom_model_cv_18_dagger_408` (website score: 0.561, 2.0 Score: 0.563)
- [ ] `ViT_L_32_imagenet1k` (website score:0.454, 2.0 Score: 0.5, 1.0 score: 0.454)
