### ISSUE TITLE
Get resent-152_v2 to Score on MajajHong2015.IT-pls

### ISSUE THREAD

**Issue by pellegreene** [brain-score/vision#856]

**Comment by pellegreene** [comment]
Moving this to "Waiting for review" because I'm waiting to hear back from Martin on the 15% variance.

**Comment by ArashAkbarinia** [comment]
Similar issues for other models:
 - ```model_score = score(model_identifier='alexnet', benchmark_identifier='Rajalingham2018public-i2n')```:
   * On [BrainScore GitHub score.ipynb](https://github.com/brain-score/vision/blob/master/examples/score.ipynb) array(0.37020821)
   * On my local machine array(0.25849674)
 - ``` - ```model_score = score(model_identifier='alexnet', benchmark_identifier='Rajalingham2018-i2n')```:```
   * On [BrainScore Leaderboard](https://www.brain-score.org/model/vision/646) .551
   * On my local machine array(0.47400355)

I would appreciate your help on that :).

**Comment by pellegreene** [comment]
Hi Arash,

Thanks for reaching out. I recommend clearing out the .results_caching directory (located in your home directory) and giving it another run. I've seen a similar issue and clearing that directory fixed it for me for some model runs.

**Comment by ArashAkbarinia** [comment]
Hi @pellegreene 
Thanks for your quick response and apologies for getting back late to you :)
I deleted the .results_caching as suggested, but the results remain the same.
Just for your information, the results are on a new virtual environment installation based on the repository's late code.
