### ISSUE TITLE
Investigate Jenkins passing incorrectly

### ISSUE THREAD

**Issue by deirdre-k** [brain-score/vision#857]
Model resnext101_32x8d_wsl passed Jenkins tests (see [PR](https://github.com/brain-score/vision/pull/834)) but should not have due to invalid ssl dependency (and possibly other issues).

Investigate why this passed Jenkins tests and fix any problems.

**Comment by samwinebrake** [comment]
All tests passed, so the run is marked as a successful run. The dependency error doesn't actually cause any failures. If this is something we would like to catch in the future, we could perhaps implement some sort of dependency check test within the generic plugin testing.
