### ISSUE TITLE
Test alexnet scoring on Rajalingham2018public-i2n

### ISSUE THREAD

**Issue by deirdre-k** [brain-score/vision#876]
Alexnet scores are not reproducing using [BrainScore GitHub score.ipynb](https://github.com/brain-score/vision/blob/master/examples/score.ipynb), thanks @ArashAkbarinia for bringing this to our attention. See context below, pulled from this [comment](https://github.com/brain-score/vision/issues/856#issuecomment-2129627287):

> 
> * `model_score = score(model_identifier='alexnet', benchmark_identifier='Rajalingham2018public-i2n'):`
>   * On [BrainScore GitHub score.ipynb](https://github.com/brain-score/vision/blob/master/examples/score.ipynb) array(0.37020821)
>   * On my local machine array(0.25849674)
> * `model_score = score(model_identifier='alexnet', benchmark_identifier='Rajalingham2018-i2n'):`
>   * On [BrainScore Leaderboard](https://www.brain-score.org/model/vision/646) .551
>   * On my local machine array(0.47400355)

We will test out scoring on our cluster setup using the scoring code directly to see if the bug reproduces. From there we should be able to narrow in on the source of the discrepancy.

**Comment by pellegreene** [comment]
@ArashAkbarinia Thanks again for bringing this to our attention! I'm running alexnet on both the public and private Rajalingham2018 benchmarks and seeing the following:

- On Rajalingham2018public-i2n (public benchmark):
The score you have listed above is for the private benchmark(i.e. the one I have below this section). To my knowledge there isn't a score on the leaderboard for Rajalingham2018public-i2n, only for Rajalingham2018-i2n. However, I was able to reproduce your score(0.2589) on my machine, too. 

- On Rajalingham2018-i2n (private benchmark):
I'm seeing a score of .370, which lines up with the leaderboard score. Where did you see that it was supposed to be 0.551? I'd like to make sure our documentation is clear if it currently isn't!

**Comment by ArashAkbarinia** [comment]
Thank you both @deirdre-k  and @pellegreene for following this issue.

I apologise, the .551 is meant to say `resnext101_32x8d_wsl` against `Rajalingham2018public-i2n`, I miswrote it in the issue as `alexnet` against `Rajalingham2018-i2n`.

The mismatches in the scores (or the confusion around it) origins from the type of dataset:
 - I cannot evaluate the model against the private benchmark `Rajalingham2018-i2n`. The error message: `Exception: [NoCredentialsError('Unable to locate credentials'), ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden')]`.
 - Therefore, I evaluated both `alexnet` and `resnext101_32x8d_wsl` against the public dataset `Rajalingham2018public-i2n`.

I understand that the private dataset is meant to be kept private to you for model evaluations. I suggest:
- Releasing a leaderboard (or simply a table of corresponding results) for the sanity check so interested users (like me) after the new install can run the code on their local machine and make sure they obtain the same numbers.
- Revising the error message for private datasets to make it more intuitive
- Changing the example in `score.ipynb` to the public dataset of Rajalingham2018.

Thanks :)

**Comment by pellegreene** [comment]
Hi Arash! 

The leaderboard on the website reflects model scores on private benchmarks exclusively, so there currently is no way to evaluate against a public one. That being said, I see what you mean. I'm able to reproduce the scores you are seeing on my machine(i.e. 0.474 with `resnext101_32x8d_wsl ` and 0.2585 with `alexnet` on `Rajalingham2018public-i2n`). So it seems that we are lining up and, like you said, it is an issue surrounding the type of benchmark. 

We appreciate those suggestions, I'll be bringing them to the engineering team and we will try to find a way to communicate these public benchmark scores.

**Comment by deirdre-k** [comment]
Working on creating those public scores in issue #890, thank you for the feedback!

**Comment by pellegreene** [comment]
As this is being addressed in the above issues, I'm going to move this to done. Thanks!
